# Convert int to float
num = 10
num_float = float(num)
print(num_float)  # 10.0

# Convert float to int
height = 5.9
height_int = int(height)
print(height_int)  # 5

# Convert int to string
age = 24
age_str = str(age)
print(age_str)  # "24"

# Convert string to int
num_str = "100"
num_int = int(num_str)
print(num_int)  # 100

# Convert list to tuple
fruits = ["Apple", "Banana"]
fruits_tuple = tuple(fruits)
print(fruits_tuple)  # ('Apple', 'Banana')
